{% set version = "1.15.1" %}
{% set release = "1" %}
{% set sha256 = "e18754d4e2c9cd385c26b84b232f602021083147e3b93d6e35ce9071e943e81f" %}
{% set so = "3" %}

package:
  name: m2w64-htslib
  version: {{ version }}

build:
  number: {{ release }}
  run_exports:
    - {{ pin_subpackage('m2w64-htslib', max_pin='x.x') }}
  skip: True  # [not win]

source:
  url: https://github.com/TileDB-Inc/m2w64-htslib-build/releases/download/{{ version }}-{{ release }}/m2w64-htslib-{{ version }}-{{ release }}.tar.gz
  sha256: {{ sha256 }}

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\bin\hts-{{ so }}.dll exit 1
    - if not exist %LIBRARY_PREFIX%\include\htslib\hfile.h exit 1
    - if not exist %LIBRARY_PREFIX%\lib\hts-{{ so }}.lib exit 1

about:
  home: https://github.com/samtools/htslib
  summary: C library for high-throughput sequencing data formats.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/TileDB-Inc/m2w64-htslib-build
  doc_url: http://www.htslib.org/
  description: |
    The conda binary m2w64-htslib bundles a pre-built htslib binary that was
    built under msys2. All dependencies are statically linked, with the
    exception of .DLLs provided by Windows. It is suitable for linking against
    in conda recipes that build using MSVC

extra:
  recipe-maintainers:
    - dhoke4tdb
    - ihnorton
    - jdblischak
    - shelnutt2
