azure:
  store_build_artifacts: True
channels:
  sources:
    - conda-forge
  targets:
    - ["jdblischak", "main"]
github:
  user_or_org: jdblischak
  branch_name: main
  tooling_branch_name: main
provider:
  win_64: azure
skip_render:
  - LICENSE.txt
upload_on_branch:
  - main
  - jdblischak
